name: Build & Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 1. Setup Buildx for caching (prevents 5GB re-builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 2. Login using your Custom Secret
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      # 3. Build & Push using your hardcoded tag
      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          # ADD THIS LINE BELOW
          context: . 
          push: true
          tags: ghcr.io/omsenjalia/debain-node:latest         # re-installing node_modules if they haven't changed!
          cache-from: type=gha
          cache-to: type=gha,mode=max
